### PR TITLE
Add params to test command

### PR DESCRIPTION
**Pull request by alxshelepenok**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Description

Added `packages` and `coverage` parameters.

### CODE REVIEW

**Comment by alxshelepenok** [comment]
@felicianotech fixed merge conflict

**Comment by jeff-knurek** [comment]
I was just about to work on a similar PR. But looking at this it's still not even close to "usable" _(usable by us 😄 )_

maybe you can introduce these other options... 🙏 
```yaml
        parameters:
          code_path:
            description: which tests to run
            type: string
            default: "./..."
          race:
            description: run tests with -race option
            type: boolean
            default: false
          count:
            description: run each test and benchmark n times
            type: string
            default: "1"
          failfast: do not start new tests after the first test failure
            description:
            type: boolean
            default: false
          short: tell long-running tests to shorten their run time
            description:
            type: boolean
            default: false
          parallel:
            description:  |
              Allow parallel execution of test functions that call t.Parallel.
              The value of this flag is the maximum number of tests to run
              simultaneously
            type: string
            default: "1"
          coverprofile:
            description: file to save coverage profile
            type: string
            default: "cover-source.out"
          covermode:
            description: flag to set the coverage mode (the default is: "set", unless -race is enabled, in which case it is "atomic")
            type: enum
            enum: ["set", "count", "atomic"]
            default: "set" 
        steps:
          - run:
              command: >-
                go test
                <<# parameters.race >>-race<</ parameters.race >>
                -count=<<parameters.count>>
                -coverprofile=<<parameters.coverprofile>>
                <<# parameters.failfast >>-failfast<</ parameters.failfast >>
                <<# parameters.short >>-short<</ parameters.short >>
                -p <<parameters.parallel>>
                -covermode=<<parameters.covermode>>
                <<parameters.code_path>>
              name: '[go] Test'
```

---
of course there's still other parameters that might be helpful to other people too.... https://golang.org/cmd/go/

**Comment by KyleTryon** [comment]
@jeff-knurek If you have a PR with these changes we would be happy to review it. It seems this is a more compatible path.

**Comment by jeff-knurek** [comment]
@KyleTryon added a PR with those changes

**Comment by felicianotech** [comment]
Thank you but we're going to go with PR #21 instead.

**Pull request closed without merging**
