### PR TITLE
Refactored Orb to use Docker Hum cimg

### LINKED ISSUE #1: Utilize new cimg docker image executor
https://github.com/CircleCI-Public/go-orb/blob/master/orb.yml#L14

Update language orbs to utilize the new cimg

**Dockerhub:** https://hub.docker.com/u/cimg
**cimg beta announcement:** https://discuss.circleci.com/t/new-convenience-image-alpha-preview-ready-for-testing/31364

Ensure tags are parameterized.

Any PRs made in service of this issue will be held until cimg docker images are ready for release.

### PR DESCRIPTION
**Pull request by caseydbrown**
Resolves #1

### CODE REVIEW

**Comment by caseydbrown** [comment]
#1

**Comment by felicianotech** [comment]
Hi, can you please fix the merge conflict?

**Comment by caseydbrown** [comment]
@felicianotech Resolved merge conflict.

**Comment by felicianotech** [comment]
Thank you for your contribution!

**Pull request merged**
